# This is a basic workflow to help you get started with Actions
name: Release Sign-In
run-name: Deploy Sign-In (${{ inputs.tag }}) to ${{ inputs.environment }} by @${{ github.actor }}

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
      environment:
        type: environment
        
env:
  proj: hi-${{ inputs.environment }}
  
jobs:
  setup:
      name: Setup Environment
      runs-on: ubuntu-latest
      steps:
        - run: echo doing setup ${{env.proj}}
        
        - name: Print env
          run: 'echo THIS IS ENV: [${{inputs.environment}}]'
          
        - name: Determine development build
          if: inputs.environment == dev
          run: echo "WE ARE DEV"

        - name: Determine production build
          if: ${{ inputs.environment == 'staging' }} || ${{ inputs.environment == 'production' }}
          run: echo "WE ARE NOT DEV"
          
  deploy-canary:
      name: Deploy Canary
      runs-on: ubuntu-latest
      needs: setup
      environment: Dev
      steps:
        - run: echo doing deploy-canary
  deploy-stable:
      name: Deploy Stable
      runs-on: ubuntu-latest
      needs: deploy-canary
      if: ${{ success() }}
      environment: Dev
      steps:
        - run: echo doing deploy-stable
  rollback-canary:
    name: Rollback
    runs-on: ubuntu-latest
    needs: deploy-stable
    if: ${{ failure() && needs.deploy-stable.result == 'failure' }}
    steps:
      - run: echo doing rollback-canary
  success:
    name: Successful Deployment
    runs-on: ubuntu-latest
    needs: deploy-stable
    if: ${{ success() && needs.deploy-stable.result == 'success' }}
    steps:
      - run: echo this was a success
