# This is a basic workflow to help you get started with Actions
name: Release Sign-In

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Image Tag:
        required: true
        type: string
      Environment:
        type: environment
  
jobs:
  setup:
      runs-on: ubuntu-latest
      steps:
        - run: doing setup
  deploy-canary:
      runs-on: ubuntu-latest
      needs: setup
      environment: Dev
      steps:
        - run: doing deploy-canary
  deploy-stable:
      runs-on: ubuntu-latest
      needs: deploy-canary
      if: ${{ success() }}
      environment: Dev
      steps:
        - run: doing deploy-stable
  rollback-canary:
    runs-on: ubuntu-latest
    needs: deploy-canary
    if: ${{ failure() }}
    steps:
      - run: echo asked for approval 2
