# This is a basic workflow to help you get started with Actions
name: Release Sign-In

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Image Tag:
        required: true
        type: string
      Environment:
        type: environment
  
jobs:
  Approve-Canary:
      runs-on: ubuntu-latest
      environment: Dev
      steps:
        - run: echo asked for approval 1
  rollback:
    needs: Approve-Canary
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - run: echo asked for approval 2
  deploy:
    needs: Approve-Canary
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - run: echo asked for approval 2
