# This is a basic workflow to help you get started with Actions
name: Release Sign-In

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Image Tag:
        required: true
        type: string
      Environment:
        type: environment
  
jobs:
  setup:
      name: Setup Environment
      runs-on: ubuntu-latest
      steps:
        - run: echo doing setup
  deploy-canary:
      name: Deploy Canary
      runs-on: ubuntu-latest
      needs: setup
      environment: Dev
      steps:
        - run: echo doing deploy-canary
  deploy-stable:
      name: Deploy Stable
      runs-on: ubuntu-latest
      needs: deploy-canary
      if: ${{ success() }}
      environment: Dev
      steps:
        - run: echo doing deploy-stable
  rollback-canary:
    name: Rollback
    runs-on: ubuntu-latest
    needs: deploy-stable
    if: ${{ failure() && needs.deploy-stable.result == 'failure' }}
    steps:
      - run: echo doing rollback-canary
  success:
    name: Successful Deployment
    runs-on: ubuntu-latest
    needs: deploy-stable
    if: ${{ success() && needs.deploy-stable.result == 'success' }}
    steps:
      - run: echo this was a success
