# This is a basic workflow to help you get started with Actions
name: testing-jn

# Controls when the workflow will run
on:
  workflow_dispatch:
  
jobs:
  approveapp:
      runs-on: ubuntu-latest
      needs: deployapp
      environment: Dev
      steps:
        - run: echo asked for approval
