# This is a basic workflow to help you get started with Actions
name: testing-jn

# Controls when the workflow will run
on:
  workflow_dispatch:
  
jobs:
  Approve-Canary:
      runs-on: ubuntu-latest
      environment: Dev
      steps:
        - run: echo asked for approval 1
  Approve-Full-Deployment:
    needs: Approve-Canary
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - run: echo asked for approval 2
